// ecommerce/backend/seedProducts.js
import mongoose from "mongoose";
import Product from "./models/Product.js";
import Category from "./models/Category.js";
import User from "./models/User.js";
import dotenv from "dotenv";

dotenv.config();

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB for Product Seeding...");

    // Clear existing products
    await Product.deleteMany({});
    console.log("Existing products cleared.");

    // Find an existing admin, or provision a temporary one to fulfill the required 'createdBy' validation
    let adminUser = await User.findOne({ role: "admin" });
    if (!adminUser) {
      adminUser = await User.create({
        name: "System Administrator",
        email: "admin@admin.com",
        password: "admin123456",
        role: "admin",
      });
      console.log("Created a fallback admin user profile for mapping dependencies.");
    }

    // Resolve Category ID assignments dynamically from database names
    const getCatId = async (name) => {
      const cat = await Category.findOne({ name });
      return cat ? cat._id : null;
    };

    const catIds = {
      smartphones: await getCatId("Smartphones"),
      accessories: await getCatId("Mobile Accessories"),
      consoles: await getCatId("Consoles"),
      games: await getCatId("Video Games"),
      watches: await getCatId("Watches"),
      headphones: await getCatId("Headphones"),
    };

    // Verify categories exist before writing products
    if (!catIds.smartphones) {
      console.error("Error: Categories not found. Please execute seedCategories.js first!");
      process.exit(1);
    }

    const products = [
      /* ──────────────── SMARTPHONES (6 items) ──────────────── */
      {
        name: "iPhone 16 Pro Max",
        brand: "Apple",
        description: "State-of-the-art smartphone featuring a durable titanium frame, a high-performance A18 Pro silicon module, and a multi-lens professional array.",
        price: 1199,
        salePrice: 1099,
        discountPercentage: 8,
        stock: 45,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 240,
        category: catIds.smartphones,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-09-20"),
        stockStatus: "in-stock",
        specifications: [{ label: "Processor", value: "A18 Pro" }, { label: "Storage", value: "256GB" }],
      },
      {
        name: "Galaxy S25 Ultra",
        brand: "Samsung",
        description: "Flagship Android device engineered with an integrated high-precision productivity stylus stylus, dynamic AMOLED screen layout, and 200MP camera resolution.",
        price: 1299,
        salePrice: null,
        discountPercentage: null,
        stock: 35,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 185,
        category: catIds.smartphones,
        createdBy: adminUser._id,
        countryOfOrigin: "Vietnam",
        releaseDate: new Date("2025-01-25"),
        stockStatus: "in-stock",
        specifications: [{ label: "Display", value: "6.8 inch AMOLED" }, { label: "RAM", value: "12GB" }],
      },
      {
        name: "Google Pixel 9 Pro",
        brand: "Google",
        description: "Pure stock Android software distribution framework backed by a dedicated Tensor chip variant optimizing high-speed computational photography routines.",
        price: 999,
        salePrice: 899,
        discountPercentage: 10,
        stock: 50,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80"],
        rating: 4.7,
        reviews: 98,
        category: catIds.smartphones,
        createdBy: adminUser._id,
        countryOfOrigin: "Taiwan",
        releaseDate: new Date("2024-08-22"),
        stockStatus: "in-stock",
        specifications: [{ label: "AI Core", value: "Tensor G4" }, { label: "Battery", value: "4700mAh" }],
      },
      {
        name: "OnePlus 13 R",
        brand: "OnePlus",
        description: "High-tier cost efficiency flagship device packed with blistering 100W wired hardware power charging mechanisms and immersive low-latency panels.",
        price: 699,
        salePrice: null,
        discountPercentage: null,
        stock: 80,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1565630916779-e303be97b6f5?w=800&auto=format&fit=crop&q=80"],
        rating: 4.6,
        reviews: 112,
        category: catIds.smartphones,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-11-05"),
        stockStatus: "in-stock",
        specifications: [{ label: "Charging", value: "100W SuperVOOC" }, { label: "Chip", value: "Snapdragon Gen 3" }],
      },
      {
        name: "Xiaomi 15 Pro Ultra",
        brand: "Xiaomi",
        description: "Uncompromised mobile optics system integration containing specialized physical aperture camera housings manufactured alongside Leica engineering.",
        price: 1099,
        salePrice: 949,
        discountPercentage: 13,
        stock: 20,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80"],
        rating: 4.7,
        reviews: 64,
        category: catIds.smartphones,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2025-02-14"),
        stockStatus: "in-stock",
        specifications: [{ label: "Lens", value: "Leica Summilux" }, { label: "Zoom", value: "5x Optical" }],
      },
      {
        name: "Nothing Phone (3)",
        brand: "Nothing",
        description: "Unique industrial layout boasting a fully transparent back interface layered with custom configurable LED alert telemetry matrices.",
        price: 599,
        salePrice: null,
        discountPercentage: null,
        stock: 0,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=800&auto=format&fit=crop&q=80"],
        rating: 4.5,
        reviews: 75,
        category: catIds.smartphones,
        createdBy: adminUser._id,
        countryOfOrigin: "India",
        releaseDate: new Date("2025-07-10"),
        stockStatus: "to-be-announced",
        specifications: [{ label: "UI", value: "NothingOS 3.0" }, { label: "Backlight", value: "Glyph Interface" }],
      },

      /* ──────────────── ACCESSORIES (6 items) ──────────────── */
      {
        name: "Anker Prime 65W Pod",
        brand: "Anker",
        description: "Ultra-compact Gallium Nitride structural assembly supplying synchronous dual USB-C distribution arrays to portable laptop configurations.",
        price: 59,
        salePrice: 49,
        discountPercentage: 16,
        stock: 150,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1622445262465-2481c4574875?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 520,
        category: catIds.accessories,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2023-04-12"),
        stockStatus: "in-stock",
        specifications: [{ label: "Technology", value: "GaN 3" }, { label: "Max Output", value: "65W Total" }],
      },
      {
        name: "MagSafe Battery Pack Pro",
        brand: "Apple",
        description: "Magnetic inductive current storage bank aligning directly over device internal inductive receiver plates cleanly.",
        price: 99,
        salePrice: null,
        discountPercentage: null,
        stock: 95,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=800&auto=format&fit=crop&q=80"],
        rating: 4.4,
        reviews: 310,
        category: catIds.accessories,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2023-09-15"),
        stockStatus: "in-stock",
        specifications: [{ label: "Capacity", value: "5000mAh" }, { label: "Mount", value: "MagSafe" }],
      },
      {
        name: "Belkin 3-in-1 Charging Stand",
        brand: "Belkin",
        description: "Premium architectural bedside console powering a smartphone, wireless earbud base, and wearable fitness tracker concurrently.",
        price: 149,
        salePrice: 129,
        discountPercentage: 13,
        stock: 40,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1622445262465-2481c4574875?w=800&auto=format&fit=crop&q=80"],
        rating: 4.7,
        reviews: 190,
        category: catIds.accessories,
        createdBy: adminUser._id,
        countryOfOrigin: "Vietnam",
        releaseDate: new Date("2024-01-10"),
        stockStatus: "in-stock",
        specifications: [{ label: "Standard", value: "Qi2 Wireless" }, { label: "Materials", value: "Stainless Steel" }],
      },
      {
        name: "Spigen Tough Armor Case",
        brand: "Spigen",
        description: "Dual-layer structural shock dissipation sheath integrating localized geometric air pockets alongside rigid outer shell frames.",
        price: 29,
        salePrice: null,
        discountPercentage: null,
        stock: 300,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=800&auto=format&fit=crop&q=80"],
        rating: 4.6,
        reviews: 840,
        category: catIds.accessories,
        createdBy: adminUser._id,
        countryOfOrigin: "South Korea",
        releaseDate: new Date("2024-09-10"),
        stockStatus: "in-stock",
        specifications: [{ label: "Drop Protection", value: "Military Grade" }, { label: "Stand", value: "Built-in Kickstand" }],
      },
      {
        name: "SanDisk 512GB MicroSDXC",
        brand: "SanDisk",
        description: "High velocity Flash storage media optimizing extreme raw file stream writes for heavy handheld console application storage mappings.",
        price: 79,
        salePrice: 59,
        discountPercentage: 25,
        stock: 400,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 1250,
        category: catIds.accessories,
        createdBy: adminUser._id,
        countryOfOrigin: "Malaysia",
        releaseDate: new Date("2023-02-18"),
        stockStatus: "in-stock",
        specifications: [{ label: "Speed Class", value: "U3 V30 A2" }, { label: "Read Velocity", value: "Up to 190MB/s" }],
      },
      {
        name: "Razer Kishi Ultra Controller",
        brand: "Razer",
        description: "Ergonomic compression vice controller expanding across type-C nodes transforming smartphones into reactive tactical gaming frames.",
        price: 149,
        salePrice: null,
        discountPercentage: null,
        stock: 65,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=800&auto=format&fit=crop&q=80"],
        rating: 4.5,
        reviews: 88,
        category: catIds.accessories,
        createdBy: adminUser._id,
        countryOfOrigin: "Taiwan",
        releaseDate: new Date("2024-04-18"),
        stockStatus: "in-stock",
        specifications: [{ label: "Interface", value: "USB-C Direct Pass" }, { label: "Audio", value: "3.5mm Port Mounted" }],
      },

      /* ──────────────── CONSOLES (5 items) ──────────────── */
      {
        name: "PlayStation 5 Slim Pro",
        brand: "Sony",
        description: "High clock computing system incorporating upgraded trace rendering core architecture logic blocks alongside 2TB solid-state internal arrays.",
        price: 699,
        salePrice: null,
        discountPercentage: null,
        stock: 25,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 450,
        category: catIds.consoles,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-11-07"),
        stockStatus: "in-stock",
        specifications: [{ label: "Storage Capacity", value: "2TB Custom NVMe" }, { label: "Output", value: "Dynamic 4K 120Hz" }],
      },
      {
        name: "Xbox Series X",
        brand: "Microsoft",
        description: "Monolithic computing block designed around 12 Teraflops of baseline processing paths supporting hardware-accelerated processing architectures.",
        price: 499,
        salePrice: 449,
        discountPercentage: 10,
        stock: 30,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=800&auto=format&fit=crop&q=80"],
        rating: 4.7,
        reviews: 890,
        category: catIds.consoles,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2020-11-10"),
        stockStatus: "in-stock",
        specifications: [{ label: "Compute Density", value: "12 TFLOP RDNA2" }, { label: "Optical Drive", value: "4K Blu-ray" }],
      },
      {
        name: "Nintendo Switch OLED Model",
        brand: "Nintendo",
        description: "Hybrid portable console sporting a vibrant 7-inch self-illuminating display layer paired with responsive sliding motion perimeter controllers.",
        price: 349,
        salePrice: null,
        discountPercentage: null,
        stock: 60,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 1420,
        category: catIds.consoles,
        createdBy: adminUser._id,
        countryOfOrigin: "Japan",
        releaseDate: new Date("2021-10-08"),
        stockStatus: "in-stock",
        specifications: [{ label: "Display Layer", value: "7.0 inch OLED" }, { label: "Internal Flash", value: "64GB Enhanced" }],
      },
      {
        name: "Steam Deck OLED 1TB",
        brand: "Valve",
        description: "Handheld x86-architecture computing node operating custom specialized Linux layers mapping PC game library environments fluidly.",
        price: 649,
        salePrice: null,
        discountPercentage: null,
        stock: 18,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 320,
        category: catIds.consoles,
        createdBy: adminUser._id,
        countryOfOrigin: "Taiwan",
        releaseDate: new Date("2023-11-16"),
        stockStatus: "in-stock",
        specifications: [{ label: "Panel", value: "90Hz HDR OLED" }, { label: "APU Engine", value: "6nm AMD Sephiroth" }],
      },
      {
        name: "Asus ROG Ally X",
        brand: "Asus",
        description: "High-density performance handheld console packing Windows operating infrastructure, custom tracking control nodes, and massive thermal fan setups.",
        price: 799,
        salePrice: 749,
        discountPercentage: 6,
        stock: 12,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80"],
        rating: 4.6,
        reviews: 145,
        category: catIds.consoles,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-07-22"),
        stockStatus: "in-stock",
        specifications: [{ label: "SoC Engine", value: "AMD Ryzen Z1 Extreme" }, { label: "Memory Block", value: "24GB LPDDR5X" }],
      },

      /* ──────────────── VIDEO GAMES (6 items) ──────────────── */
      {
        name: "Grand Theft Auto VI",
        brand: "Rockstar Games",
        description: "Next-era open sandbox environmental rendering engine set across the deeply saturated neon grid corridors of Vice City.",
        price: 69,
        salePrice: null,
        discountPercentage: null,
        stock: 500,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 9400,
        category: catIds.games,
        createdBy: adminUser._id,
        countryOfOrigin: "USA",
        releaseDate: new Date("2025-10-25"),
        stockStatus: "in-stock",
        specifications: [{ label: "Target Platform", value: "PS5 / Xbox Series X" }, { label: "Genre", value: "Action Sandbox" }],
      },
      {
        name: "Elden Ring: Shadow of the Erdtree",
        brand: "FromSoftware",
        description: "Massive dark fantasy execution environment presenting elevated challenging combat frameworks across entirely new structural map files.",
        price: 39,
        salePrice: null,
        discountPercentage: null,
        stock: 250,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 1840,
        category: catIds.games,
        createdBy: adminUser._id,
        countryOfOrigin: "Japan",
        releaseDate: new Date("2024-06-21"),
        stockStatus: "in-stock",
        specifications: [{ label: "Type", value: "Expansion Pack DLC" }, { label: "Director", value: "Hidetaka Miyazaki" }],
      },
      {
        name: "The Legend of Zelda: Tears of the Kingdom",
        brand: "Nintendo",
        description: "Acclaimed open air vehicle generation pipeline enabling complex sandbox geometry physics bindings across high-altitude sky coordinates.",
        price: 69,
        salePrice: 59,
        discountPercentage: 14,
        stock: 190,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 3200,
        category: catIds.games,
        createdBy: adminUser._id,
        countryOfOrigin: "Japan",
        releaseDate: new Date("2023-05-12"),
        stockStatus: "in-stock",
        specifications: [{ label: "Platform Reference", value: "Nintendo Switch" }, { label: "Media Format", value: "Physical Flash Cartridge" }],
      },
      {
        name: "Cyberpunk 2077: Ultimate Edition",
        brand: "CD Projekt Red",
        description: "Complete future urban dystopian narrative logic suite running complex ray path simulation rendering across heavily populated neon vectors.",
        price: 59,
        salePrice: 39,
        discountPercentage: 33,
        stock: 140,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80"],
        rating: 4.7,
        reviews: 1100,
        category: catIds.games,
        createdBy: adminUser._id,
        countryOfOrigin: "Poland",
        releaseDate: new Date("2023-12-05"),
        stockStatus: "in-stock",
        specifications: [{ label: "Engine Patch", value: "Version 2.12 Included" }, { label: "Addon Content", value: "Phantom Liberty Core" }],
      },
      {
        name: "Marvel Spider-Man 2",
        brand: "Insomniac Games",
        description: "High-velocity spatial translation engine managing dual localized character models streaming smoothly through Manhattan urban structures.",
        price: 69,
        salePrice: 49,
        discountPercentage: 28,
        stock: 85,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 1490,
        category: catIds.games,
        createdBy: adminUser._id,
        countryOfOrigin: "USA",
        releaseDate: new Date("2023-10-20"),
        stockStatus: "in-stock",
        specifications: [{ label: "SSD Optimization", value: "Zero Load Transition" }, { label: "Audio Profile", value: "3D Spatial Spatial" }],
      },
      {
        name: "Resident Evil 9: Revenant",
        brand: "Capcom",
        description: "Atmospheric tracking horror runtime executing photorealistic light scattering textures built over the modern RE Engine pipeline.",
        price: 69,
        salePrice: null,
        discountPercentage: null,
        stock: 0,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80"],
        rating: 0,
        reviews: 0,
        category: catIds.games,
        createdBy: adminUser._id,
        countryOfOrigin: "Japan",
        releaseDate: new Date("2026-03-12"),
        stockStatus: "unavailable",
        specifications: [{ label: "Framework", value: "Next-gen RE Engine" }, { label: "Perspective", value: "First Person Immersive" }],
      },

      /* ──────────────── WATCHES (6 items) ──────────────── */
      {
        name: "Apple Watch Ultra 3",
        brand: "Apple",
        description: "High-altitude micro-machined titanium capsule utilizing multi-frequency satellite positioning arrays and localized micro-LED displays.",
        price: 799,
        salePrice: null,
        discountPercentage: null,
        stock: 22,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 104,
        category: catIds.watches,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-09-20"),
        stockStatus: "in-stock",
        specifications: [{ label: "Luminance", value: "3000 nits Peak" }, { label: "Chassis", value: "Aerospace Titanium" }],
      },
      {
        name: "Galaxy Watch 7 Ultra",
        brand: "Samsung",
        description: "Ruggedized performance tracking watch operating advanced biological impedance arrays resolving precise metabolic metrics tracking loops.",
        price: 649,
        salePrice: 579,
        discountPercentage: 10,
        stock: 40,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80"],
        rating: 4.6,
        reviews: 142,
        category: catIds.watches,
        createdBy: adminUser._id,
        countryOfOrigin: "South Korea",
        releaseDate: new Date("2024-07-24"),
        stockStatus: "in-stock",
        specifications: [{ label: "Sensor Array", value: "BioActive 2" }, { label: "OS Platform", value: "WearOS 5.0" }],
      },
      {
        name: "Garmin Fenix 8 Solar",
        brand: "Garmin",
        description: "Endurance navigation device incorporating continuous solar cell current generation pathways overlaying transactional geographic matrix routing map panels.",
        price: 999,
        salePrice: null,
        discountPercentage: null,
        stock: 15,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 86,
        category: catIds.watches,
        createdBy: adminUser._id,
        countryOfOrigin: "Taiwan",
        releaseDate: new Date("2024-08-27"),
        stockStatus: "in-stock",
        specifications: [{ label: "Lens Type", value: "Power Sapphire Solar" }, { label: "Battery Span", value: "Up to 30 Days" }],
      },
      {
        name: "Fitbit Charge 6",
        brand: "Fitbit",
        description: "Streamlined low-footprint activity validation node calculating baseline pulse metrics sequences directly alongside localized navigation paths.",
        price: 159,
        salePrice: 129,
        discountPercentage: 18,
        stock: 110,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80"],
        rating: 4.4,
        reviews: 410,
        category: catIds.watches,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2023-10-12"),
        stockStatus: "in-stock",
        specifications: [{ label: "Connectivity", value: "Google Maps Sync" }, { label: "Sensors", value: "EDA & ECG Onboard" }],
      },
      {
        name: "Amazfit T-Rex 3 Pro",
        brand: "Amazfit",
        description: "Reinforced high-impact structural composite watch capable of maintaining internal operations across extreme atmospheric temperature parameters safely.",
        price: 229,
        salePrice: null,
        discountPercentage: null,
        stock: 55,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80"],
        rating: 4.5,
        reviews: 67,
        category: catIds.watches,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-09-05"),
        stockStatus: "in-stock",
        specifications: [{ label: "Water Rating", value: "10 ATM Certified" }, { label: "Battery Unit", value: "500mAh High Density" }],
      },
      {
        name: "Pixel Watch 3",
        brand: "Google",
        description: "Elegant circular profile watch framing high frequency processing nodes tightly coupled into deep ecosystem fitness services tracking loops cleanly.",
        price: 349,
        salePrice: 299,
        discountPercentage: 14,
        stock: 62,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80"],
        rating: 4.5,
        reviews: 130,
        category: catIds.watches,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-09-10"),
        stockStatus: "in-stock",
        specifications: [{ label: "Wireless Stack", value: "UWB Tracking Supported" }, { label: "Panel Frequency", value: "1-60Hz LTPO AMOLED" }],
      },

      /* ──────────────── HEADPHONES (6 items) ──────────────── */
      {
        name: "Sony WH-1000XM6",
        brand: "Sony",
        description: "Industry benchmark acoustic enclosure housing state-of-the-art hybrid noise capture processors adjusting dynamics programmatically.",
        price: 399,
        salePrice: null,
        discountPercentage: null,
        stock: 38,
        featured: true,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80"],
        rating: 4.9,
        reviews: 180,
        category: catIds.headphones,
        createdBy: adminUser._id,
        countryOfOrigin: "Malaysia",
        releaseDate: new Date("2024-08-15"),
        stockStatus: "in-stock",
        specifications: [{ label: "Audio Codec", value: "LDAC Hi-Res Wireless" }, { label: "ANC Core", value: "Dual V2 Engine" }],
      },
      {
        name: "Bose QuietComfort Ultra",
        brand: "Bose",
        description: "Ultra-premium immersive spatial audio headphones combining targeted soundstage phase emulation alongside soft micro-texture contact points.",
        price: 429,
        salePrice: 379,
        discountPercentage: 11,
        stock: 45,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 295,
        category: catIds.headphones,
        createdBy: adminUser._id,
        countryOfOrigin: "Mexico",
        releaseDate: new Date("2023-10-05"),
        stockStatus: "in-stock",
        specifications: [{ label: "Spatial Sound", value: "Bose Immersive Audio" }, { label: "Charge Lifespan", value: "Up to 24 Hours" }],
      },
      {
        name: "AirPods Max 2",
        brand: "Apple",
        description: "Anodized aluminum audio cans supporting extreme custom computational driver sound balancing and seamless switching metrics.",
        price: 549,
        salePrice: null,
        discountPercentage: null,
        stock: 20,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80"],
        rating: 4.7,
        reviews: 510,
        category: catIds.headphones,
        createdBy: adminUser._id,
        countryOfOrigin: "China",
        releaseDate: new Date("2024-09-20"),
        stockStatus: "in-stock",
        specifications: [{ label: "Port", value: "USB-C Interface" }, { label: "Processing", value: "Dual H2 Silicon Packages" }],
      },
      {
        name: "Sennheiser Momentum 4 Wireless",
        brand: "Sennheiser",
        description: "High-fidelity audiophile acoustic structural tuning delivering an industry-leading 60-hour internal playback capability map loop.",
        price: 379,
        salePrice: 299,
        discountPercentage: 21,
        stock: 70,
        featured: false,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80"],
        rating: 4.8,
        reviews: 420,
        category: catIds.headphones,
        createdBy: adminUser._id,
        countryOfOrigin: "Romania",
        releaseDate: new Date("2022-08-23"),
        stockStatus: "in-stock",
        specifications: [{ label: "Playback Battery", value: "60 Hours Benchmark" }, { label: "Driver Size", value: "42mm Transducer System" }],
      },
      {
        name: "Sony WF-1000XM5 Earbuds",
        brand: "Sony",
        description: "True wireless inner-ear modules embedding bone conduction vibration telemetry alongside high-density physical foam noise isolation caps.",
        price: 299,
        salePrice: 249,
        discountPercentage: 16,
        stock: 130,
        featured: true,
        onSale: true,
        images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80"],
        rating: 4.6,
        reviews: 610,
        category: catIds.headphones,
        createdBy: adminUser._id,
        countryOfOrigin: "Malaysia",
        releaseDate: new Date("2023-07-27"),
        stockStatus: "in-stock",
        specifications: [{ label: "Driver Architecture", value: "Dynamic Driver X" }, { label: "Mic Configuration", value: "6 Mics With AI Processing" }],
      },
      {
        name: "Audio-Technica ATH-M50xBT2",
        brand: "Audio-Technica",
        description: "Wireless adaptation of studio-standard monitoring headphones delivering flat, authentic response signals across the full auditory matrix spectrum.",
        price: 199,
        salePrice: null,
        discountPercentage: null,
        stock: 90,
        featured: false,
        onSale: false,
        images: ["https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=800&auto=format&fit=crop&q=80"],
        rating: 4.7,
        reviews: 340,
        category: catIds.headphones,
        createdBy: adminUser._id,
        countryOfOrigin: "Taiwan",
        releaseDate: new Date("2021-08-31"),
        stockStatus: "in-stock",
        specifications: [{ label: "Driver Element", value: "45mm Rare Earth Magnets" }, { label: "DAC Chipset", value: "AK4331 Onboard Converter" }],
      },
    ];

    await Product.insertMany(products);
    console.log(`Successfully seeded ${products.length} comprehensive data assets into the database!`);
    process.exit(0);
  } catch (error) {
    console.error("Critical error seeding products:", error);
    process.exit(1);
  }
}

seedProducts();